#!/bin/bash

echo "🧹 BookMate Project Cleanup Script"
echo "===================================="
echo ""
echo "This will DELETE files marked as safe to remove."
echo "Backup exists at: ~/Desktop/BookMate-webapp-backup-*"
echo "Git commit: 6ca758b (can revert with: git reset --hard 6ca758b)"
echo ""

# Count files to be deleted
total_files=0

# Function to safely remove file if it exists
remove_file() {
    if [ -f "$1" ]; then
        rm "$1"
        echo "✓ Removed: $1"
        ((total_files++))
    fi
}

# Function to safely remove directory if it exists
remove_dir() {
    if [ -d "$1" ]; then
        rm -rf "$1"
        echo "✓ Removed directory: $1"
        ((total_files++))
    fi
}

echo "Starting cleanup..."
echo ""

# ===== ROOT LEVEL MARKDOWN FILES =====
echo "📝 Removing documentation files..."

remove_file "ADMIN_PAGE_THEME_UPDATE.md"
remove_file "ALL_MOBILE_ISSUES_RESOLVED.md"
remove_file "API_ENABLEMENT_VERIFICATION.md"
remove_file "API_HEALTH_CHECK_REPORT.md"
remove_file "APPS_SCRIPT_DEPLOYMENT_DIAGNOSIS.md"
remove_file "APPS_SCRIPT_HTTP_302_FIX.md"
remove_file "APPS_SCRIPT_UPDATE_OVERHEAD_CATEGORIES.md"
remove_file "APPS_SCRIPT_V8.6_TRANSFER_VERIFICATION.md"
remove_file "APPS_SCRIPT_V9.0_DEPLOYMENT.md"
remove_file "APPS_SCRIPT_V9.0_IMPLEMENTATION_COMPLETE.md"
remove_file "APPS_SCRIPT_V9.0_PM_SUMMARY.md"
remove_file "BALANCE_100_PERCENT_VERIFICATION.md"
remove_file "BALANCE_AUDIT_COMPLETE.md"
remove_file "BALANCE_LOGIC_VERIFICATION.md"
remove_file "BALANCE_PAGE_CACHE_FIX.md"
remove_file "BALANCE_PAGE_COMPREHENSIVE_REPORT.md"
remove_file "BALANCE_QA_IMPLEMENTATION_COMPLETE.md"
remove_file "BALANCE_QA_QUICK_REF.md"
remove_file "BALANCE_SYSTEM_QA_REPORT.md"
remove_file "BALANCE_SYSTEM_V9_VERIFICATION.md"
remove_file "BALANCE_SYSTEM_V9_VERIFICATION_REPORT.md"
remove_file "BANK_ACCOUNT_SYNC_COMPLETE.md"
remove_file "BOOKMATE_BRAND_KIT_IMPLEMENTATION.md"
remove_file "BOOKMATE_WEBAPP_COMPLETE_MAP.md"
remove_file "BRAND_IMPLEMENTATION_COMPLETE.md"
remove_file "BRAND_IMPLEMENTATION_PLAN.md"
remove_file "BRAND_KIT_COMPLETE_REFERENCE.md"
remove_file "BRAND_PALETTE_IMPLEMENTATION.md"
remove_file "BRAND_REDESIGN_COMPLETE.md"
remove_file "BUILD_ERROR_CACHE_FIX.md"
remove_file "CACHE_BUSTING_IMPLEMENTATION.md"
remove_file "CATEGORY_MANAGEMENT_COMPLETE.md"
remove_file "CATEGORY_SYNC_FLOW.md"
remove_file "CHART_BRAND_KIT_ALIGNMENT.md"
remove_file "COMPLETE_GOP_FIX_SUMMARY.md"
remove_file "COMPLETE_PHASE_VERIFICATION_REPORT.md"
remove_file "COMPLETE_SYSTEM_AUDIT.md"
remove_file "COMPLETE_TEST_RESULTS.md"
remove_file "CONFIG_FILE_STRATEGY.md"
remove_file "CONTENT_TYPE_FIX_COMPLETE.md"
remove_file "CRITICAL_SECRET_MISMATCH_DIAGNOSIS.md"
remove_file "CRITICAL_VALIDATION_BUG_FIXED.md"
remove_file "DARK_THEME_DESIGN_SYSTEM.md"
remove_file "DASHBOARD_API_FIX.md"
remove_file "DASHBOARD_BALANCE_FIX.md"
remove_file "DASHBOARD_EXPENSE_FIX_COMPLETE.md"
remove_file "DASHBOARD_GOP_FIX_COMPLETE.md"
remove_file "DASHBOARD_PERFORMANCE_OPTIMIZATION.md"
remove_file "DATA_SOURCE_CHEATSHEET.md"
remove_file "DATA_SOURCE_REFERENCE.md"
remove_file "DEPLOYMENT_COMPLETE.md"
remove_file "DEPLOYMENT_GUIDE_TRANSFER_OPERATION.md"
remove_file "DEPLOYMENT_SETUP.md"
remove_file "DEPLOYMENT_STATUS_PM_FIX.md"
remove_file "DEPLOYMENT_SUMMARY.md"
remove_file "DEPLOYMENT_SUMMARY_DROPDOWN_SYNC.md"
remove_file "DEPLOYMENT_SUMMARY_NOV_3_2025.md"
remove_file "DEPRECATION_AND_MIGRATION_COMPLETE.md"
remove_file "DROPDOWN_SYNC_COMPLETE.md"
remove_file "DUAL_DEPLOYMENT_COMPLETE.md"
remove_file "DUAL_DEPLOYMENT_QUICK_REF.md"
remove_file "DUAL_DEPLOYMENT_SUCCESS.md"
remove_file "EXPENSE_CATEGORY_MANAGEMENT.md"
remove_file "FINAL_INTEGRATION_COMPLETE.md"
remove_file "FIREBASE_BLAZE_UPGRADE.md"
remove_file "FIREBASE_MOBILE_CONFIG.md"
remove_file "FIREBASE_PHASE4_QUICK.md"
remove_file "FIREBASE_PHASE4_SETUP.md"
remove_file "FIREBASE_SETUP_COMPLETE.md"
remove_file "FIREBASE_SPARK_IMPLEMENTATION.md"
remove_file "FIREBASE_SUCCESS_SUMMARY.md"
remove_file "FONT_INSTALLATION_GUIDE.md"
remove_file "GOOGLE_SHEETS_DATA_CORRUPTION.md"
remove_file "GOOGLE_SHEETS_INTEGRATION_COMPLETE.md"
remove_file "GOOGLE_SHEETS_TROUBLESHOOTING.md"
remove_file "GOP_CALCULATION_CORRECTED.md"
remove_file "IMPLEMENTATION_COMPLETE.md"
remove_file "ISSUE_2_RESOLVED.md"
remove_file "ISSUE_OWNERSHIP.md"
remove_file "JSON_PARSE_ERROR_FIX.md"
remove_file "LOADING_SCREEN_IMPLEMENTATION.md"
remove_file "LOADING_SCREEN_VISUAL_SUMMARY.md"
remove_file "LOCAL_TESTING_COMPLETE.md"
remove_file "LOCAL_TEST_RESULTS.md"
remove_file "LOGO_INTEGRATION_COMPLETE.md"
remove_file "LOGO_VISUAL_SUMMARY.md"
remove_file "MANUAL_TEST_GUIDE_PNL_LIVE.md"
remove_file "MOBILE_APP_HANDOFF_SUMMARY.md"
remove_file "MOBILE_APP_INTEGRATION_GUIDE.md"
remove_file "MOBILE_APP_QUICK_REFERENCE.md"
remove_file "MOBILE_APP_TEAM_UPDATE.md"
remove_file "MOBILE_APP_TRANSFER_UPDATE_V9.1.md"
remove_file "MOBILE_ISSUES_INDEX.md"
remove_file "MOBILE_TEAM_API_INTEGRATION_GUIDE.md"
remove_file "MOBILE_TEAM_BALANCE_API_UPDATE.md"
remove_file "MOBILE_TEAM_DATA_GUIDE.md"
remove_file "MOBILE_TEAM_ISSUES_COMPLETE_REPORT.md"
remove_file "MOBILE_TEAM_ISSUES_RESOLUTION.md"
remove_file "MOBILE_TEAM_MESSAGE.md"
remove_file "MOBILE_TEAM_MIGRATION_SUMMARY.md"
remove_file "MOBILE_TEAM_NOTIFICATION.md"
remove_file "MOBILE_TEAM_OVERHEAD_EXPENSES_FIX.md"
remove_file "MOBILE_TEAM_PROPERTY_PERSON_FIX.md"
remove_file "MOBILE_TEAM_QUICK_REF.md"
remove_file "MOBILE_TEAM_UPDATE_API_CATEGORIES_ALL.md"
remove_file "MOBILE_TEAM_UPDATE_NOV4.md"
remove_file "NAMED_RANGES_AUTOFIX_COMPLETE.md"
remove_file "NAMED_RANGES_CORRECTION_REPORT.md"
remove_file "NAME_CONSISTENCY_AUDIT_COMPLETE.md"
remove_file "NET_PROFIT_CHART_VERIFICATION.md"
remove_file "OFFICIAL_DECISION_API_OPTIONS.md"
remove_file "OVERHEAD_PROPERTY_FIX_COMPLETE.md"
remove_file "OVERHEAD_SEPARATION_AUDIT_COMPLETE.md"
remove_file "PAYMENT_TYPES_API_FIX.md"
remove_file "PAYMENT_TYPES_IMPLEMENTATION_COMPLETE.md"
remove_file "PERFORMANCE_IMPROVEMENTS_DEPLOYED.md"
remove_file "PERFORMANCE_OPTIMIZATION_COMPLETE.md"
remove_file "PERFORMANCE_OPTIMIZATION_PLAN.md"
remove_file "PHASE1_BRAND_REDESIGN_COMPLETE.md"
remove_file "PHASE1_COMPLETE_SUMMARY.md"
remove_file "PHASE1_DYNAMIC_OPTIONS_INTAKE.md"
remove_file "PHASE1_SUCCESS_RESPONSE.md"
remove_file "PHASE2_COMPLETE_SUMMARY.md"
remove_file "PHASE2_CYAN_TO_YELLOW_COMPLETE.md"
remove_file "PHASE2_IMPLEMENTATION_GUIDE.md"
remove_file "PHASE2_QUICK_START.md"
remove_file "PHASE2_TEST_RESULTS.md"
remove_file "PHASE2_VISUAL_ARCHITECTURE.md"
remove_file "PHASE3_ARCHITECTURE.md"
remove_file "PHASE3_FIREBASE_SETUP.md"
remove_file "PHASE3_IMPLEMENTATION_PLAN.md"
remove_file "PHASE3_QUICK_START.md"
remove_file "PHASE3_README.md"
remove_file "PHASE5_COMPLETE_SUMMARY.md"
remove_file "PHASE5_DEPLOYMENT_READY.md"
remove_file "PHASE5_ENDPOINT_VERIFICATION.md"
remove_file "PHASE5_IMPLEMENTATION_CHECKLIST.md"
remove_file "PHASE5_MOBILE_CODE_EXAMPLES.md"
remove_file "PHASE5_MOBILE_INTEGRATION_GUIDE.md"
remove_file "PHASE5_QUICK_REFERENCE.md"
remove_file "PHASE5_README.md"
remove_file "PHASE5_WHAT_WE_ACCOMPLISHED.md"
remove_file "PIE_CHART_REMOVAL_COMPLETE.md"
remove_file "PM_ENDPOINT_COMPARISON.md"
remove_file "PM_FINAL_CONFIRMATION.md"
remove_file "PM_FIX_ALL_PAYMENT_TYPES.md"
remove_file "PM_INFORMATION_REQUEST_RESPONSE.md"
remove_file "PM_REQUIREMENTS_IMPLEMENTED.md"
remove_file "PM_REVIEW_PACKAGE.md"
remove_file "PM_TRANSFER_ISSUE_RESOLUTION.md"
remove_file "PM_TRANSFER_ISSUE_SUMMARY.md"
remove_file "PM_VISUAL_SUMMARY.md"
remove_file "PNL_DATA_ANALYSIS.md"
remove_file "PNL_DATA_FLOW_DIAGNOSIS.md"
remove_file "PNL_FIX_COMPLETE.md"
remove_file "PNL_LIVE_API_IMPLEMENTATION.md"
remove_file "PNL_LIVE_FRONTEND_COMPLETE.md"
remove_file "PNL_LIVE_INTEGRATION_SUMMARY.md"
remove_file "PNL_MOBILE_DISPLAY_DIAGNOSIS.md"
remove_file "PNL_OVERHEAD_DYNAMIC_CATEGORIES.md"
remove_file "PNL_PAGE_BRAND_KIT_COMPLETE.md"
remove_file "PRODUCTION_DEPLOYMENT_CHECKLIST.md"
remove_file "PRODUCTION_DEPLOYMENT_READY.md"
remove_file "PRODUCTION_DEPLOYMENT_SUCCESS.md"
remove_file "PRODUCTION_DEPLOYMENT_SUCCESS_FINAL.md"
remove_file "PROPERTY_MAPPING_BUG_FIX.md"
remove_file "PROPERTY_PERSON_API_FIX_ANALYSIS.md"
remove_file "PROPERTY_PERSON_API_FIX_DEPLOYED.md"
remove_file "QUICK_DEPLOYMENT_CHECKLIST.md"
remove_file "README_BALANCE_QA.md"
remove_file "README_PHASE2.md"
remove_file "REBRANDING_COMPLETE.md"
remove_file "ROOT_CAUSE_SHEET_NOT_SHARED.md"
remove_file "SERVER_SETUP_COMPLETE.md"
remove_file "SERVICE_ACCOUNT_CONFIG.md"
remove_file "SERVICE_ACCOUNT_TEST_RESULTS.md"
remove_file "SETTINGS_404_CLEANUP.md"
remove_file "SETTINGS_PAGE_API_RESULTS.md"
remove_file "SETTINGS_PAGE_THEME_UPDATE.md"
remove_file "SYNC_SHEETS_GUIDE.md"
remove_file "TEST_SUITE_MONTH_FORMAT_FIX.md"
remove_file "TEXT_COLOR_FIX_COMPLETE.md"
remove_file "THEME_UPDATE_PROGRESS.md"
remove_file "TRANSFER_CATEGORIES_MANUAL_GUIDE.md"
remove_file "TRANSFER_DEPLOYMENT_STEPS.md"
remove_file "TRANSFER_FINAL_IMPLEMENTATION.md"
remove_file "TRANSFER_IMPLEMENTATION_SUMMARY.md"
remove_file "TRANSFER_QUICK_REF.md"
remove_file "TWO_DEPLOYMENTS_CONFIG.md"
remove_file "UNIFIED_BALANCE_IMPLEMENTATION_STATUS.md"
remove_file "UNIFIED_BALANCE_README.md"
remove_file "UNIFIED_BALANCE_SYSTEM_COMPLETE.md"
remove_file "URGENT_API_ENDPOINT_DECISION.md"
remove_file "URGENT_API_OPTIONS_PAYMENT_TYPES_MISSING.md"
remove_file "URGENT_PM_PRODUCTION_BLOCKER_REPORT.md"
remove_file "URGENT_THEME_FIX_COMPLETE.md"
remove_file "V8_VS_V9_COMPARISON.md"
remove_file "V9_BALANCE_SYSTEM_DEPLOYMENT_GUIDE.md"
remove_file "V9_BALANCE_SYSTEM_IMPLEMENTATION_SUMMARY.md"
remove_file "V9_QUICK_START.md"
remove_file "V9_VISUAL_ARCHITECTURE.md"
remove_file "VERCEL_ENDPOINT_TEST_RESULTS.md"
remove_file "VERCEL_ENV_CRITICAL_FIX.md"
remove_file "VERCEL_ENV_FIX_COMPLETE.md"
remove_file "VIEW_ALL_BUTTON_RESTORED.md"
remove_file "WATCH_MODE_COMPLETE.md"
remove_file "WATCH_MODE_DEPLOYMENT.md"
remove_file "WEBAPP_API_USAGE_AUDIT.md"
remove_file "WEBAPP_BALANCE_PAGE_VERIFICATION.md"
remove_file "WEBAPP_DARK_THEME_UPDATE.md"
remove_file "WEBAPP_ISSUES_ACTION_PLAN.md"
remove_file "WEBAPP_TEAM_CONNECTION_CHECKLIST.md"
remove_file "WEBAPP_TEAM_INFO_FOR_PM.md"
remove_file "WEBAPP_TEAM_REQUIREMENTS.md"
remove_file "WEBAPP_TRANSFER_IMPLEMENTATION.md"
remove_file "WEBAPP_UPDATED_TO_UNIFIED_BALANCE.md"
remove_file "WEBHOOK_SECRET_AUTH_ANALYSIS.md"
remove_file "WEB_TEAM_STATUS_REPORT.md"

# ===== BACKUP FILES =====
echo ""
echo "💾 Removing backup files..."

remove_file "COMPLETE_APPS_SCRIPT_V7_WITH_BALANCE.backup.1761816320140.js"
remove_file "COMPLETE_APPS_SCRIPT_V7_WITH_BALANCE.backup.1761817091981.js"
remove_file "COMPLETE_APPS_SCRIPT_V7_WITH_BALANCE.backup.1762262761.js"
remove_file "COMPLETE_APPS_SCRIPT_V7_WITH_BALANCE.js"
remove_file "APPS_SCRIPT_COMPLETE_WITH_V9.js"
remove_file "APPS_SCRIPT_OVERHEAD_EXPENSES.js"
remove_file "APPS_SCRIPT_V9_NEW_BALANCE_SYSTEM.js"
remove_file "app/activity/page-old-activity-log.tsx.backup"
remove_file "app/balance/page-old-input.tsx"
remove_file "app/balance/page-old-v8.tsx"
remove_file "app/balance/page.tsx.backup-1762268290"
remove_file "app/balance/page.tsx.bak"
remove_file "app/settings/page.tsx.backup"
remove_file "app/settings/page.tsx.backup2"
remove_file "app/settings/page.tsx.final"
remove_file "app/api/pnl/namedRanges/route.ts.backup"
remove_file "app/api/pnl/overhead-expenses/route.ts.backup"
remove_file "app/api/pnl/property-person/route.ts.backup"
remove_file "app/api/sheets/route.ts.backup"
remove_file "components/settings/RevenueManager.tsx.backup"

# ===== TEST/DEBUG SCRIPTS =====
echo ""
echo "🧪 Removing test/debug scripts..."

remove_file "analyze-q-column.js"
remove_file "automated-test-runner.js"
remove_file "browser-inspection-test.js"
remove_file "check-all-apis.sh"
remove_file "check-all-sheets.js"
remove_file "check-data-sheet.js"
remove_file "check-dropdown-ranges.js"
remove_file "check-expense-structure.js"
remove_file "check-named-ranges.js"
remove_file "check-q31.js"
remove_file "check-row-80.js"
remove_file "check-row31-data.js"
remove_file "check-sheet-headers.js"
remove_file "check-sheets-all-categories.js"
remove_file "check-sheets-payments.js"
remove_file "clear-q59.js"
remove_file "compare-endpoints.sh"
remove_file "fetch-fresh-dropdowns.js"
remove_file "fix-apps-script-redirects.sh"
remove_file "fix-content-type.sh"
remove_file "fix-overhead-ranges.js"
remove_file "fix-slate-colors.sh"
remove_file "generate-pnl-formulas.js"
remove_file "migrate-dark-theme.sh"
remove_file "monitor-servers.sh"
remove_file "revert-overhead-ranges.js"
remove_file "set-base-url.sh"
remove_file "STAGING_TRANSFER_TESTS.js"
remove_file "sync-from-sheets.js"
remove_file "test-all.js"
remove_file "test-balance-system.sh"
remove_file "test-data-columns.js"
remove_file "test-deployment.sh"
remove_file "test-dual-deployments.sh"
remove_file "test-mobile-viewport.js"
remove_file "test-overhead-modal.js"
remove_file "test-payment-extraction.js"
remove_file "test-production-endpoints.sh"
remove_file "test-quick-entry-flow.js"
remove_file "test-service-account.js"
remove_file "test-sheets-data.js"
remove_file "test-vercel-endpoints.sh"
remove_file "test-watch-mode.sh"
remove_file "TRANSFER_VERIFICATION_TESTS.js"
remove_file "update-colors.sh"
remove_file "update-ranges-from-sheets.js"
remove_file "validate-pnl-structure.js"
remove_file "verify-all-in-sync.js"

# ===== LOG FILES =====
echo ""
echo "📊 Removing log files..."

remove_file "complete-test-results.log"
remove_file "dev-server.log"
remove_file "dev.log"
remove_file "pglite-debug.log"
remove_file "test-results-1762261323.log"
remove_file "sync-report-1761816320142.json"
remove_file "sync-report-1761816590324.json"
remove_file "sync-report-1761817091984.json"
remove_file "sync-report-1762056116786.json"
remove_file "sync-report-1762056208462.json"

# ===== FOLDERS =====
echo ""
echo "📁 Removing unused folders..."

remove_dir "api-health-check-results"
remove_dir "endpoint-comparison-results"
remove_dir "app/upload-old"
remove_dir "app/balance-test"
remove_dir "app/review"
remove_dir "assets"
remove_dir ".expo"
remove_dir ".stfolder"

# ===== FONT PLACEHOLDERS =====
echo ""
echo "🎨 Removing font placeholders..."

remove_file "app/fonts/PLACEHOLDER-Aileron-Bold.txt"
remove_file "app/fonts/PLACEHOLDER-Aileron-Regular.txt"
remove_file "app/fonts/PLACEHOLDER-BebasNeue-Regular.txt"
remove_file "app/fonts/PLACEHOLDER-MadeMirage-Bold.txt"
remove_file "app/fonts/PLACEHOLDER-MadeMirage-Regular.txt"

# ===== HIDDEN/SYNC FILES =====
echo ""
echo "🔧 Removing sync/hidden files..."

find . -name ".DS_Store" -type f -delete
remove_file ".server.pid"
remove_file ".stignore"
remove_file ".syncthing.QUICK_REFERENCE.md.tmp"
remove_file ".vercel-trigger"
remove_file "Balance_System_Template.xlsx"

# ===== SUMMARY =====
echo ""
echo "===================================="
echo "✅ Cleanup Complete!"
echo "===================================="
echo ""
echo "Files/folders removed: $total_files+"
echo ""
echo "Next steps:"
echo "1. Review the project structure"
echo "2. Run 'git status' to see changes"
echo "3. If happy, commit with: git add -A && git commit -m 'Clean up project files'"
echo "4. If not happy, revert with: git reset --hard 6ca758b"
echo ""
